### ISSUE TITLE
How to change the scale type of imageview?

### ISSUE THREAD

**Issue by devabir93** [AgnaldoNP/PreviewImageCollection#1]
Hello,
I see that the image view has scaleType of CenterCrop, so how to change the scale type of imageview?

Thanks

**Comment by AgnaldoNP** [comment]
Sorry for answer it so late.

Actually there is no easy way to do it. I've used center crop top ensure that any image will cover all of their space and don't show any black/white borders. 

By the way, I can provide this features in a new version.

**Comment by AgnaldoNP** [comment]
This option was added in the verson **1.3**

**Comment by devabir93** [comment]
I back to check if you find a solution, Thank you soooo much, you are the best guys.
