### ISSUE TITLE
Replace Bitmap with URL

### ISSUE THREAD

**Issue by 0975086498** [AgnaldoNP/PreviewImageCollection#2]
I think you should replace HashMap<BitMap, Image> by HashMap<URL, Image>.
Then you can use Glide to load BitMap from URL.
Because When I have 10 Image to preview and i limit to show only 4 (+6 morer). I still have to add 10 Bitmap to but it just need 4 BitMap to enough to show. This thing may make OOM when I have many PreviewImageCollection like NewsFeed facebook. 

If I use 10 URL it just 10 String and it does not occupy memory

Ps: My English so bad...wish you sympathize...Thank you

**Comment by AgnaldoNP** [comment]
Hi, 
Thanks for the suggestion. I've improved the library adding glide on version **1.3**,
now you can add a new image passing Uri, Bitmap, Drawable, File or Image Resource Id.

Please let me know if you find some bug :)
