### ISSUE TITLE
Any chance of a Java sample?? 

### ISSUE THREAD

**Issue by Pealy** [AgnaldoNP/PreviewImageCollection#3]
I really like this way of displaying and want to use it my own app but I don't know Kotlin. If there's any chance of a simple Java sample instead of Kotlin I'd be really grateful. I just can't seem to get this bit into Java:

collectionView.addImage(BitmapFactory.decodeResource(resources, R.drawable.landscape_08),
            object : ImageCollectionView.OnImageClickListener {
                override fun onClick(bitmap: Bitmap, imageView: ImageView) {
                    Toast.makeText(imageView.context, "Test Click image 08", Toast.LENGTH_LONG)
                        .show()
                }
            }
        )

**Comment by AgnaldoNP** [comment]
Hi, the last grey box in the README.md is an example of java usage, I think you didn't see it. I need to make it clear there ;)
