### ISSUE TITLE
Not support to preview server Image

### ISSUE THREAD

**Issue by Rishabhsaxena2011** [AgnaldoNP/PreviewImageCollection#5]
Library is good its not support images which we comes from server

**Comment by AgnaldoNP** [comment]
Can you provide an example of how you have tried it?

**Comment by Krutika-chotara** [comment]
How to load image from server url ?

**Comment by AgnaldoNP** [comment]
Hi, Starting from version 1.9 you can call `addimage(url, drawabalePlaceHolderId)`
