### ISSUE TITLE
Reference to source files

### ISSUE THREAD

**Issue by andreasflosdorf** [AgnaldoNP/PreviewImageCollection#8]
I have multiple jpg images that I decode to bitmaps like  `BitmapFactory.decodeFile(file.getPath());`  before loading them into the gallery via  `imageCollectionView.addImage(bitmap, null, new OnImageLongClickListener...);`. So far so good.
Now I want to delete a specific picture, not only remove the bitmap from the gallery. I want to delete the source file (see above `file.getPath()`) inside a  `OnImageLongClickListener`.  
However, I am missing a reference to the file. Is it possible to reference a jpg file loaded into the Gallery backwards?

**Comment by AgnaldoNP** [comment]
Hi,
Unfortunately this is not possible for now. I would sugest you to create your own LongClickListener by extending OnImageLongClickListener and storing the file reference
